name : Docker Assignment 2

on:
  push:
    branches: [ main ]
  pull_request:
     branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Image
        run:  |
          echo ${{ secrets.DOCKERPW }} | docker login --username "subhasish30" --password-stdin
          docker image build -t subhasish30/hello-world-app:latest .
          docker push subhasish30/hello-world-app:latest
